version: "3"

services: 
    client:
        image: client
        restart: always
        ports: 
            - "3001:3000"
        volumes: 
            - ./client:/client
            - /client/node_modules
    server:
        image: server
        restart: always
        ports: 
            - "5001:5000"
        volumes: 
            - ./server:/server
            - /server/node_modules